# Command `./build/markdown2confluence -l .github/confluence-ep.yml`
space: GOMARKDOWN
title: demo-confluence-yaml
#file: README.md
#ancestor:
debug: false
#since:
username: ben.smith.developer@gmail.com
endpoint: https://golang-markdown-to-confluence.atlassian.net/wiki
parent: "Demo Parent"
source:
  - README.md
parent_config:
  - confluence-ep.yml # run directory